// Generated by tools/build-event-data.cjs from data/events/halloween2026.json.
globalThis.EventData = {
  "halloween26": {
    "id": "halloween26",
    "label": "Halloween 2026",
    "status": "upcoming",
    "defaultEnabled": false,
    "auras": []
  }
};
